name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  tests:
    name: integration-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: npm install
        run: npm install

      - name: Run integration test
        run: npm test

